# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZGpotFJjrk17PzC2tqnAi8d1UrSS1/8ohhMlFhkxgfZ/Oyu12YzsgdyWGbh/q+1TH7KTyOWDOIuNAvBzV+lF4s5aAUTKIUwt2NWwAYYENiIW78pSnkED161r7EFdO4tcLx0JKF7ewUF3E2QY//Sbe1Tl/R7mS8SV6/S94LAeVAziciW829EvE/3/LotUoaJYMka42CbFhrkHj1cET0trC/OHl2jBm/N1hED9pKXIavd9zvE4gzHMnNktAxT3eFQbaa4O62AhczZPuwAQ7NDzq/4C1J5bU+xdVV7dRLmXv3nB+XvUzK3QIWqi2YL5z6skj8Lmdq+wTAZ5lRdyL52X80H2T14Vgqpy8TDqxoqHYdDzZj+QxoGJ4x6faWXrrrzV+47/QZbwBGNryV4ztAfceg0MbiRVxPzNomMTWJz90OwnmXZzBD4rC+TYl3BERVHvmzrh0jtxPutAK1IvJjrU7zS4dGLs1RnnA0CkEANOYRD3r+enKMmo3bWtictRvJCBowqli29gI1fFSltvM9w+WLQ7LG1r6uROdfn6KJUZ9HOMvHEwd2zJBusAVkNICGA8Olll51CUfcH3mQmP8TehLUc98oq8ZKzaOyGL13h1yzbd3CTjz8tNKvFAsa1GxZBeC7Oii21refcS0fRPb0z5eGQvAnOOIevm/LIrnVLXir0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
