# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rOHjC8vTsop/qibgLIrPSBJv+rqDtKyBjDVPcvE2nqFhxQdmZwignjD2ZnG7mh/FWQQTw7uX0CLCDkXW0nbSjwxySABOvWVxKVNfIO5OCa2iio5ZEi6HkPbm8PlSlk5f+PChM1ltqXnyS/dh5inTTE3GqHC5S3vTjmk1gwbRYUfD+RnCj6cMYRwpbzhJvrq7f3QsRmkYq1wFrsu0QXjbfgzufi0AtLw7+/kiw+DxJIIr63GNi+vtnCIJmvDp7W6t0egfy+Sjs9bSv89RYJH1ZoLsqdFufa0WcSCkp4MfokhVwru6ZPsAcXKo+OB3AXhpQMsqPmQTHTbklmCZEQtqS3O72wG0i/JtfSk2kTD6TbXDlSUF8GDo/KVE+JeT09c9baMmU9neJLgVxZbwnAaRDWBiBL8F9HHnHZQkn46TobnmSvcJ9LGXbR499sJxUg9BkmcdqhMEAgvBWmq4/aeYyBTXu9x6x4EpINGptQ0cDojTAlmg/qWfvH9IXwxD2OkNora2W8P8PxkEfsufJiz/fgaD3Ef55o2WXQpf97p3MQ6EqlfRII79xGY4vcTrtepAh6AiznhJsxDfJPu1sT9pnRYHWKszw7cBs/XNLcjDFPeStzVOrX/18yBkR5m02Ks0PBW4rrU5MdhunOLcLHD1NOpF42hQFEy0n3ObB6Pu3p4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
